apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    app: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec: 
      containers:
      - name: home
        image: bradfordmedeiros/nodogma-home:0.2
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "curl https://gist.githubusercontent.com/BradfordMedeiros/15bf84fc7dcb1cf4119c188f41bf9461/raw/bd4ddf8beb918ff52054299610d0edcca4fef396/gistfile1.txt > /usr/share/nginx/html/extra-style.css"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/redirects.js
          name: home-config
          subPath: config
      volumes:
      - name: home-config
        configMap:
          name: home-redirect-configmap


