apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec: 
      containers:
      - name: prometheus
        image: prom/prometheus:v2.5.0
        readinessProbe:
            httpGet:
              path: /monitoring/graph
              port: 9090
        ports:
        - containerPort: 9090
        args:
        - --config.file
        - /etc/prometheus/prometheus.yml
        - --web.external-url
        - /monitoring

