apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
     nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
  - http: 
      paths: 
#      - path: /monitoring/*
#        backend: 
#          serviceName: prometheus-service
#          servicePort: 9090
      - path: /hippo
        backend: 
          serviceName: hippo-service
          servicePort: 8000
      - path: /bootstrapper
        backend:
          serviceName: bootstrapper-service
          servicePort: 8001          
      - path: /
        backend:
          serviceName: home-service
          servicePort: 8080
